baseURL = "http://davelongman.com"
languageCode = "en-GB"
title = "The blog of Dave Longman" 
theme = "ananke"
copyright = "Dave Longman"
enableGitInfo = true
enableRobotsTXT = true
enableEmoji = true

[languages]
[languages.en]
    title = "Dave Longman" # this is the text in the top left of the page

[taxonomies]
    tags = "tags"

[markup.goldmark.renderer]
    unsafe = true

[sitemap]
    changefreq = "daily"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    date_format = "2 January 2006"
    description = "Possibly useful things I've learnt"
    # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    # background_color_class = "bg-mid-gray"
    recent_posts_number = 8

[params.ananke.social.follow]
    new_window_icon = false
    networks = [
        "linkedin",
        "github",
        "twitter"
        ]
[params.ananke.social.github]
    username = "dlongman"
[params.ananke.social.twitter]
    username = "dlongman"
[params.ananke.social.linkedin]
    username = "davelongman"
    #url = "https://www.linkedin.com/in/davelongman/"